version: '3.2'

services:
  local-office-search-api:
    container_name: local-office-search-api
    image: "local-office-search-api${SEARCH_API_VERSION_TAG}"
    command: rails server -p 3060 -b 0.0.0.0
    tmpfs: /app/tmp
    user: root
    ports:
      - 3060
    environment:
      - LOCAL_OFFICE_SEARCH_TEST_DB_HOST=db
      - LOCAL_OFFICE_SEARCH_TEST_DB_PORT=5432
      - LOCAL_OFFICE_SEARCH_EPISERVER_USER=unittest
      - LOCAL_OFFICE_SEARCH_EPISERVER_PASSWORD=ci
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgis/postgis:14-3.2"
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=local_office_search_api_testing
      - POSTGRES_USER=local_office_search_api
      - POSTGRES_PASSWORD=testing
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
