version: "3.2"
services:
  local-office-search-api:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY_DOMAIN:-979633842206.dkr.ecr.eu-west-1.amazonaws.com}/local-office-search-api:develop
        - ${DOCKER_REGISTRY_DOMAIN:-979633842206.dkr.ecr.eu-west-1.amazonaws.com}/local-office-search-api${SEARCH_API_PR_TAG}
        - ${DOCKER_REGISTRY_DOMAIN:-979633842206.dkr.ecr.eu-west-1.amazonaws.com}/local-office-search-api${SEARCH_API_VERSION_TAG}
    image: local-office-search-api${SEARCH_API_VERSION_TAG}
    container_name: local-office-search-api.test
    command: rails server -b 0.0.0.0 -p 3060
    labels:
      traefik.port: 3060
      traefik.backend: local-office-search-api
      traefik.frontend.rule: 'Host: local-office-search-api.test'
      traefik.enable: true
    links:
      - api-proxy
    tmpfs: /app/tmp
    user: root
    ports:
      - 3060
    environment:
      - SEARCH_DB_HOST=db
      - SEARCH_DB_PORT=5432
      - SEARCH_DB_USER=local_office_search_api
      - SEARCH_DB_PASSWORD=develop
      - SEARCH_DB_NAME=local_office_search_api
      - SEARCH_TEST_DB_HOST=testdb
      - SEARCH_TEST_DB_PORT=5432
      - SEARCH_TEST_DB_USER=local_office_search_api
      - SEARCH_TEST_DB_PASSWORD=testing
      - SEARCH_TEST_DB_NAME=local_office_search_api_testing
    volumes:
      - .:/app
      - ~/.aws:/home/ruby/.aws
    depends_on:
      - db
      - testdb

  api-proxy:
    image: traefik:alpine
    command: --configFile=/traefik.toml
    container_name: api-proxy.test
    ports:
      - "3060:3060"
      - "8181:8181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  db:
    image: "postgis/postgis:14-3.2"
    ports:
      - "5460:5432" # expose on a port so we can run things locally
    environment:
      - POSTGRES_DB=local_office_search_api
      - POSTGRES_USER=local_office_search_api
      - POSTGRES_PASSWORD=develop

  testdb:
    image: "postgis/postgis:14-3.2"
    ports:
      - "5462:5432" # expose on a port so our IDE etc can run tests against the db
    environment:
      - POSTGRES_DB=local_office_search_api_testing
      - POSTGRES_USER=local_office_search_api
      - POSTGRES_PASSWORD=testing

