version: '3.2'

services:
  search-api:
    build: .
    container_name: search-api.test
    image: "search-api${SEARCH_API_VERSION_TAG}"
    command: rails server -p 3060 -b 0.0.0.0
    labels:
      - "traefik.port=3060"
      - "traefik.backend=search-api"
      - "traefik.frontend.rule=Host: search-api.test"
      - "traefik.enable=true"
    links:
      - api-proxy
    tmpfs: /app/tmp
    user: root
    ports:
      - 3060
    environment:
      - SEARCH_DB_HOST=db
      - SEARCH_DB_USER=postgres
      - SEARCH_DB_PASSWORD=test
    env_file:
      - ./docker/test.env
    volumes:
      - .:/app
    depends_on:
      - db

  api-proxy:
    image: traefik:alpine
    command: --configFile=/traefik.toml
    container_name: api-proxy.test
    ports:
      - "3060:3060"
      - "8181:8181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  db:
    image: "postgres:10-alpine"
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=test
