---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/status":
    get:
      summary: Checks system status
      responses:
        '200':
          description: Service is available
        '503':
          description: Service is unavailable
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
