---
openapi: 3.0.1
info:
  title: Local Office Search API
  version: v1
paths:
  "/status":
    get:
      summary: Checks system status
      responses:
        '200':
          description: Service is available
  "/api/v1/offices/{id}":
    get:
      summary: Retrieves a single office
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Fetches a single office
          content:
            application/json:
              schema:
                "$schema": https://json-schema.org/draft/2019-09/schema
                "$id": https://local-office-search.citizensadvice.org.uk/schemas/v1/office
                type: object
                properties:
                  id:
                    type: string
                  member_id:
                    type:
                    - string
                    - 'null'
                  name:
                    type: string
                  about_text:
                    type:
                    - string
                    - 'null'
                  accessibility_information:
                    type: array
                    items:
                      type: string
                  street:
                    type:
                    - string
                    - 'null'
                  city:
                    type:
                    - string
                    - 'null'
                  county:
                    type:
                    - string
                    - 'null'
                  postcode:
                    type:
                    - string
                    - 'null'
                  location:
                    type:
                    - 'null'
                    - "$id": https://geojson.org/schema/Point.json
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                          - Point
                        coordinates:
                          type: array
                          items:
                            type: number
                          minItems: 2
                          maxItems: 2
                      required:
                      - type
                      - coordinates
                      additionalProperties: false
                  email:
                    type:
                    - string
                    - 'null'
                  website:
                    type:
                    - string
                    - 'null'
                  phone:
                    type:
                    - string
                    - 'null'
                  opening_hours:
                    type: object
                    properties:
                      information:
                        type:
                        - string
                        - 'null'
                      monday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      tuesday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      wednesday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      thursday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      friday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      saturday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      sunday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                    required:
                    - information
                    - monday
                    - tuesday
                    - wednesday
                    - thursday
                    - friday
                    - saturday
                    - sunday
                    additionalProperties: false
                  telephone_advice_hours:
                    type: object
                    properties:
                      information:
                        type:
                        - string
                        - 'null'
                      monday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      tuesday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      wednesday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      thursday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      friday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      saturday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                      sunday:
                        type:
                        - 'null'
                        - type: object
                          properties:
                            opens:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                            closes:
                              type: string
                              pattern: "^\\d{2}:\\d{2}:\\d{2}$"
                          required:
                          - opens
                          - closes
                          additionalProperties: false
                    required:
                    - information
                    - monday
                    - tuesday
                    - wednesday
                    - thursday
                    - friday
                    - saturday
                    - sunday
                    additionalProperties: false
                required:
                - id
                - member_id
                - name
                - about_text
                - accessibility_information
                - street
                - city
                - postcode
                - location
                - email
                - website
                - phone
                - opening_hours
                - telephone_advice_hours
                additionalProperties: false
        '302':
          description: Allows you to look up an office by its resource directory ID
            and redirect to canonical ID
        '404':
          description: No office with this ID
          content:
            application/json:
              schema:
                "$schema": https://json-schema.org/draft/2019-09/schema
                "$id": https://www.rfc-editor.org/rfc/rfc7807
                type: object
                properties:
                  type:
                    type: string
                    format: uri
                  title:
                    type: string
                  status:
                    type: number
                required:
                - type
                additionalProperties: false
  "/api/v1/offices/":
    get:
      summary: Retrieves a single office
      parameters:
      - name: q
        in: query
        required: true
        description: the search terms to use
        schema:
          type: string
      responses:
        '200':
          description: a list of search results
          content:
            application/json:
              schema:
                "$schema": https://json-schema.org/draft/2019-09/schema
                "$id": https://local-office-search.citizensadvice.org.uk/schemas/v1/results
                type: object
                properties:
                  match_type:
                    type: string
                    enum:
                    - exact
                    - fuzzy
                    - unknown
                    - out_of_area_scotland
                    - out_of_area_ni
                    description: "\n                                * `exact` means
                      the search term matched an exact location, so only offices which
                      serve the exact location\n                                   are
                      shown (this could include no locations).\n                                *
                      `fuzzy` means the search term matched a wider locality and not
                      an individual point, so the results may\n                                   include
                      offices which can not serve that exact location.\n                                *
                      `unknown` means the search term was unable to be interpreted
                      or matched to a location\n                                  (so
                      there are no results).\n                                * `out_of_area_scotland`
                      and `out_of_area_ni` means the search term matched exactly,
                      but to a location in\n                                  Scotland
                      or Northern Ireland which is not in the network coverage area.\n
                      \                               "
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                      required:
                      - id
                      additionalProperties: false
                required:
                - match_type
                - results
                additionalProperties: false
        '400':
          description: If query is not specified
          content:
            application/json:
              schema:
                "$schema": https://json-schema.org/draft/2019-09/schema
                "$id": https://www.rfc-editor.org/rfc/rfc7807
                type: object
                properties:
                  type:
                    type: string
                    format: uri
                  title:
                    type: string
                  status:
                    type: number
                required:
                - type
                additionalProperties: false
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
