[tool.poetry]
name = "corporate-webhooks"
version = "0.1.0"
description = "CDK app for the Local Office Search API project"
authors = ["Citizens Advice"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
ca-cdk-constructs = {git = "https://github.com/citizensadvice/ca-cdk-constructs", rev = "v0.14.0"}
ca-cdk8s-constructs = { git = "https://github.com/citizensadvice/ca-cdk8s-constructs", rev = "v2.3.0" }
ruff = "^0.11.13"
cdk8s-plus-32 = "^2.1.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"

[tool.ruff]
target-version = 'py312'
line-length = 95

[tool.ruff.lint]
select = ['E', 'W', 'F', 'C', 'N', 'INP']
ignore = ['E501']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
