name: Dev Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build Image
    runs-on: runs-on
    permissions:
      id-token: write
      contents: read
      issues: read
    steps:
      - name: Build and push to ECR
        uses: citizensadvice/build-and-private-ecr-push-action@v1
        with:
          role_arn: "arn:aws:iam::979633842206:role/LocalOfficeSearchApiDeployment"
          dockerfile_context: "."
          repository_name: local-office-search-api
          multiarch_build: "disabled"
          prod_image: true
          auth_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy dev
    needs:
      - build
    uses: ./.github/workflows/deploy_stage.yml
    with:
      stage: dev
