name: Prod Deployment

on:
  workflow_run:
    workflows: ["Dev Deployment"]
    types:
      - completed
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy infrastructure and chart
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: runs-on
    permissions:
      id-token: write
      contents: read
    environment:
      name: prod
    steps:
      - name: Sleep for 1 minute
        run: echo "Waiting for 60 seconds to allow for abort of prod deployment" && sleep 60
        shell: bash

      - uses: actions/checkout@v4

      - uses: citizensadvice/python-poetry-setup-action@v1
        with:
          install_cdk: true
          project_root: "./cdk"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/LocalOfficeSearchApiDeployment"
          role-session-name: local-office-search-api-deploy-prod-workflow
          aws-region: eu-west-1

      - name: Deploy CDK
        run: |
          set -eo pipefail
          cd ./cdk
          poetry run cdk deploy "prod/**" LocalOfficeSearchApiEcrRepo --concurrency 2 --ci --require-approval never

  slack-success:
    name: Slack Notification (Success)
    needs: deploy
    runs-on: runs-on
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@v1
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          channel_id: "C02K26YCER1" #content-platform_builds
          title: ":rocket: Deployed Prod: Local Office Search API :rocket:"
          message: |
            The Local Office Search API on *prod* has been deployed!

  slack-failure:
    name: Slack Notification (Failure)
    needs: deploy
    runs-on: runs-on
    if: failure()
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@v1
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          channel_id: "C02K26YCER1" #content-platform_builds
          title: ":fire: Deploy failed (PROD): Local Office Search API :fire:"
          message: |
            The Local Office Search API on dev failed to deploy :pensive:
