name: Prod Deployment

on:
  workflow_run:
    workflows: ["Dev Deployment"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy prod
    uses: ./.github/workflows/deploy_stage.yml
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      stage: prod
    secrets: inherit
